#!/bin/bash

FileName="$(date '+%Y%m%d%H%M%S.png')"

setsid -f mpv --no-video ~/.local/share/sounds/menu1.mp3
shotgun -g "$(hacksaw)" ~/Sync/Pictures/Screenshots/"$FileName"
feh ~/Sync/Pictures/Screenshots/"$FileName"
