#!/bin/sh

source "$XDG_CONFIG_HOME"/pf/shell-config.sh

setsid -f mpv --no-video "$XDG_DATA_HOME"/sounds/menu1.mp3

declare -a options=(
        "Aseprite"
        "Blender"
        "Gimp"
        "Krita"
)

choice=$(printf '%s\n' "${options[@]}" | ${MENU} 'Projects: ')

case "$choice" in
    "Aseprite")
        cd "$ART_FOLDER"
        AsepriteChoice=$(printf '%s\n' "$(find ./ | grep '.ase' | cut -c 3-)" | ${MENU} 'Aseprite: ')
        setsid -f aseprite "$ART_FOLDER"/"$AsepriteChoice"
    ;;

    "Blender")
        cd "$ART_FOLDER"
        BlenderChoice=$(printf '%s\n' "$(find ./ | grep '.blend' | cut -c 3-)" | ${MENU} 'Blender: ')
        setsid -f blender "$PROJECTS_FOLDER"/"$BlenderChoice"
    ;;

    "Gimp" )
        cd "$ART_FOLDER"
        GimpChoice=$(printf '%s\n' "$(find ./ | grep '.xcf' | cut -c 3-)" | ${MENU} 'Gimp: ') 
        setsid -f gimp "$PROJECTS_FOLDER"/"$GimpChoice"
    ;;

    "Krita" )
        cd "$ART_FOLDER"
        KritaChoice=$(printf '%s\n' "$(find ./ | grep '.kra' | cut -c 3-)" | ${MENU} 'Krita: ')
        setsid -f krita "$PROJECTS_FOLDER"/"$KritaChoice"
esac

setsid -f mpv --no-video "$XDG_DATA_HOME"/sounds/menu2.mp3

