#!/bin/sh

source "$XDG_CONFIG_HOME"/pf/shell-config.sh

setsid -f mpv --no-video "$XDG_DATA_HOME"/sounds/menu1.mp3
python3 "$DWM"/dmenu/etc/steam_dmenu.py -d "$MENU" -l "$STEAM_LIBRARY"
setsid -f mpv --no-video "$XDG_DATA_HOME"/sounds/menu2.mp3
