format = """
[░▒▓](background)\
$username\
[](bg:red fg:white)\
$directory\
[](fg:red bg:blue)\
$git_branch\
$git_status\
[](fg:blue bg:green)\
$nodejs\
$rust\
$golang\
$php\
[ ](fg:green)\
"""

[directory]
style = "fg:white bg:red"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[username]
style_user = "bg:white fg:black"
style_root = "bg:black fg:white"
format = '[ ]($style)[$user]($style)[ ]($style)'
show_always = true

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:white bg:blue)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:white bg:blue)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol ($version) ](fg:white bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol ($version) ](fg:white bg:green)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:green"
format = '[[ $symbol ($version) ](fg:white bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol ($version) ](fg:white bg:green)]($style)'
