format = """
[░▒▓](background)\
[  ](bg:white fg:black)\
[](bg:blue fg:white)\
$directory\
[](fg:blue bg:green)\
$git_branch\
$git_status\
[](fg:green bg:blue)\
$nodejs\
$rust\
$golang\
$php\
[](fg:blue bg:green)\
[ ](fg:green)\
"""


#[ $USER ](bg:#b8c0e0 fg:#1e2030)\
#$time\
[directory]
style = "fg:white bg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:white bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:white bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:white bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:white bg:blue)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:white bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:white bg:blue)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
